# Extra autostart processes
# exec-once = uwsm-app -- my-service
exec-once = "walker --gapplication-service"

# rose-pine-cursor
exec-once = hyprctl setcursor rose-pine-hyprcursor 28

# # spotify minimized
# exec-once = spotify --minimized

# perplecity minimized
exec-once = omarchy-launch-webapp "https://perplexity.ai"
