# Rose Pine Moon Theme Colors
$surface = rgb(2a273f)
$text = rgb(e0def4)
$rose = rgb(ea9a97)

general {
    hide_cursor = true
    grace = 2
    disable_loading_bar = true
}

background {
    monitor =
    path = screenshot # Blurs your current screen
    blur_passes = 3
    blur_size = 8
}

# Time
label {
    monitor =
    text = $TIME
    color = $text
    font_size = 90
    font_family = MartianMono Nerd Font
    position = 0, 80
    halign = center
    valign = center
}

# Input Field
input-field {
    monitor =
    size = 250, 50
    outline_thickness = 3
    dots_size = 0.2
    dots_spacing = 0.5
    outer_color = $rose
    inner_color = $surface
    font_color = $text
    fade_on_empty = false
    placeholder_text = <span foreground="##908caa">Password...</span>
    position = 0, -20
    halign = center
    valign = center
}
