windowrule = tag +pygame, match:title (?i)pygame.?window
windowrule = tag -default-opacity, match:tag pygame
windowrule = fullscreen on, match:tag pygame
windowrule = workspace 10, match:tag pygame
windorrule = match:class ^(Spotify)$, workspace special:music silent
windowrule = match:tag quickchat, workspace special:aichat silent
windowrule = match:tag scratchpad, workspace special:scratchpad silent
windowrule {
name = btop-size
match:initial_class = org.omarchy.btop
match:title = btop
min_size = (monitor_w*0.6) (monitor_h*0.7)
center = on
}
windowrule {
  name = jolt-size
  match:initial_class = org.omarchy.jolt
  match:initial_title = Ghostty
  float = on
  min_size = (monitor_w*0.5) (monitor_h*0.6)
  max_size = (monitor_w*0.7) (monitor_h*0.7)
  center = on
}
