
###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = foot
$fileManager = thunar
$menu = fuzzel
$browser = brave

$mainMod = SUPER # Sets "Windows" key as main modifier
$altMod = ALT


#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hypr.land/Configuring/Environment-variables/

env = XCURSOR_THEME=rose-pine-hyprcursor
env = XCURSOR_SIZE=24
# env = HYPRCURSOR_THEME,BreezeX-RosePine-Linux
# env = HYPRCURSOR_SIZE,24
env = QT_QPA_PLATFORM, wayland
env = QT_QPA_PLATFORMTHEME, gtk3
env = GDK_BACKEND, wayland, x11
env = GTK_THEME, rose-pine-moon-gtk:dark
